site_name: ROS and ISAAC-ROS Documentation
site_url: https://Kenn3o3.github.io/isaac-ros/  # Update this if deploying to GitHub Pages
theme:
  name: material  # Change to 'mkdocs' if not using Material theme
nav:
  - Home: index.md
  - Isaac Sim ROS Documentation:
      - Installation: Isaac_doc/1_doc.md
      - "URDF Import: Turtlebot": Isaac_doc/2_doc.md
      - Driving TurtleBot via ROS2 messages: Isaac_doc/3_doc.md
      - ROS 2 Cameras: Isaac_doc/4_doc.md
      - Publishing Camera’s Data: Isaac_doc/5_doc.md
      - ROS2 Clock: Isaac_doc/6_doc.md
  - ROS 2 Humble Documentation:
      - Installation: ROS_doc/1_doc.md
      - CLI tools:
          - Configuring environment: ROS_doc/2_doc.md#configuring-environment
          - Using `turtlesim`, `ros2`, and `rpt`: ROS_doc/2_doc.md#using-turtlesim-ros2-and-rpt
          - Understanding nodes: ROS_doc/2_doc.md#understanding-nodes
          - Understanding topics: ROS_doc/2_doc.md#understanding-topics
          - Understanding services: ROS_doc/2_doc.md#understanding-services
          - Understanding parameters: ROS_doc/2_doc.md#understanding-parameters
          - Understanding actions: ROS_doc/2_doc.md#understanding-actions
          - Using `rqt_console` to view logs: ROS_doc/2_doc.md#using-rqt_console-to-view-logs
          - Launching nodes: ROS_doc/2_doc.md#launching-nodes
          - Recording and playing back data: ROS_doc/2_doc.md#recording-and-playing-back-data
markdown_extensions:
  - toc:
      permalink: true